"""add test cases to exercises

Revision ID: 1becf11620b9
Revises: 41601ba5ea72
Create Date: 2026-08-07 04:51:59.364831

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1becf11620b9'
down_revision: str | Sequence[str] | None = '41601ba5ea72'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "exercises",
        sa.Column(
            "test_cases",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )

    op.alter_column(
        "exercises",
        "test_cases",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'test_cases')
    # ### end Alembic commands ###
