"""add user id to exercises

Revision ID: ee3f614858d3
Revises: 1becf11620b9
Create Date: 2026-08-08 13:12:55.169515

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ee3f614858d3'
down_revision: str | Sequence[str] | None = '1becf11620b9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('user_id', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_exercises_user_id'), 'exercises', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercises_user_id'), table_name='exercises')
    op.drop_column('exercises', 'user_id')
    # ### end Alembic commands ###
